const seudo = "mehdi";
let niveau = 999;
let age = 20;
let score = 5600;
const pays = "maroc";
console.log("Pseudo :" + seudo)
console.log("niveau :" + niveau)
console.log("age :" + age)
console.log("score :" + score)
console.log("pays :" + pays)
